name: Deploy on GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      - name: Use Node.js
        uses: actions/setup-node@v3.3.0
        with:
          node-version: lts/*

      - name: Install packages
        run: npm ci

      - name: Build app
        run: npm run build && npm run export && touch ./out/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: out
          target-folder: .
